### ISSUE TITLE
npm run sonus

### ISSUE THREAD

**Issue by Mattmildren** [evancohen/smart-mirror#635] opened 2017-04-13 01:35 UTC
This seems to keep showing up and I think it might be why my microphone doesnt work. Any solutions?

pi@raspberrypi:~/smart-mirror $ npm run sonus

> smart-mirror@0.0.12 sonus /home/pi/smart-mirror
> node sonus.js

fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/pi/smart-mirror/keyfile.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (/home/pi/smart-mirror/sonus.js:13:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "sonus"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! smart-mirror@0.0.12 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.12 sonus script 'node sonus.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node sonus.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smart-mirror/npm-debug.log

**Comment by justbill2020** [comment] 2017-04-13 03:02
please search other issues prior to opening a new issue this is a duplicate of #633.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Closed by justbill2020** 2017-04-13 03:02 UTC
