### ISSUE TITLE
Problem trying to use Remote to configure!

### ISSUE THREAD

**Issue by MaxSpiegs** [evancohen/smart-mirror#586] opened 2017-02-15 06:09 UTC
Hello,

First, thanks for everything! Tutorial was incredibly helpful! Everything runs and works yet the only problem I have lies here in the fact that, upon using the remote on my computer and attempting to configure the functions, I am presented with this error:
> Entered

 content is not yet a valid JSON Form object.

The JSON Form library returned:
TypeError: $(...).jsonForm is not a function
    at n. (http://130.215.212.136:8080/config-client.js:59:25)
    at n.emit (http://130.215.212.136:8080/socket.io/socket.io.js:2:28725)
    at n.onevent (http://130.215.212.136:8080/socket.io/socket.io.js:3:5720)
    at n.onpacket (http://130.215.212.136:8080/socket.io/socket.io.js:3:5342)
    at n. (http://130.215.212.136:8080/socket.io/socket.io.js:3:7486)
    at n.emit (http://130.215.212.136:8080/socket.io/socket.io.js:2:28725)
    at n.ondecoded (http://130.215.212.136:8080/socket.io/socket.io.js:1:29250)
    at s. (http://130.215.212.136:8080/socket.io/socket.io.js:3:7486)
    at s.r.emit (http://130.215.212.136:8080/socket.io/socket.io.js:1:23662)
    at s.add (http://130.215.212.136:8080/socket.io/socket.io.js:1:10407)

> 
Any help would be most appreciated! Thanks!

**Comment by justbill2020** [comment] 2017-02-15 07:07
So, this is odd. we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time. Let's troubleshoot this tomorrow.

**Comment by evancohen** [comment] 2017-02-15 23:14
Did this get resolved?

**Comment by justbill2020** [comment] 2017-02-16 00:13
Not as of yet I've not seen @maxSpiegs on discord and I can't reproduce the behavior. also there's insufficient data as the issue template was ignored... 

I would close it and hopefully he will follow up on discord and if we confirm there's a bug we can reopen.

**Closed** 2017-02-16 01:42 UTC

**Comment by sdetweil** [comment] 2018-05-11 13:35
please reopen, this is occurring again, also on previous installed and working system

**Comment by sdetweil** [comment] 2018-05-11 14:01
the jsonform repo in on blacklist

https://gitcdn.xyz/repo/joshfire/jsonform/master/lib/jsonform.js

Forbidden - This repo/gist is on the blacklist. If you wish to appeal, please open an issue here: https://github.com/schme16/gitcdn.xyz/issues, with why you feel this repo should not be on the blacklist.
