### ISSUE TITLE
Error everything during npm install

### ISSUE THREAD

**Issue by Laubre** [evancohen/smart-mirror#188] opened 2016-03-26 19:03 UTC
Hi, i have now already reinstalled my system 4 times, always following your installation guide, but whenever i am at the "npm install" point, i get the same error.. I have no idea how to fix it, but it gives me this error log file.
Maybe anyone here has an idea on how to fix it 

[npm-debug.txt](https://github.com/evancohen/smart-mirror/files/190591/npm-debug.txt)

Thanks in advance :+1:

**Comment by evancohen** [comment] 2016-03-26 21:39
Dupe of #189

**Closed by evancohen** 2016-03-26 21:39 UTC
