### ISSUE TITLE
Hotword detection issues

### ISSUE THREAD

**Issue by petran1420** [evancohen/smart-mirror#429] opened 2016-11-11 04:17 UTC
I seem to be experiencing a problem a few others are dealing with, but perhaps for different reasons, so let me explain my situation specifically. 

When I boot up the app with `npm start` voice recognition typically works right off the bat, with hotword detection working quite well, listening to commands afterwards and such (but it can never seem to understand the word 'zoom' when I try to zoom in or out of a map, hah). However at some point, sometimes 5 minutes, sometimes 2 minutes, hotword detection appears to have stopped working. I also noticed that about half the time the 'grey glow' that acknowledges the system is listening is turned on immediately when i run the app, before I even say anything. Also, when the detection stops working the grey glow usually doesn't go away.  

I just ran `npm run sonus` and see that I get a positive `!h: 1` for a hotword recognition, and things like `!p: call` and `!p: come on` when it hears other things. However if I leave it alone I'll sporadically get a positive `!h: 1` outputs even if I don't say anything. 

Running the dev console currently. The microphone appears to be listening constantly...It will give out the voice command options to 'what can I say' even if I don't say 'smart mirror' beforehand, or the 'grey glow' will activate if I say anything, not just 'smart mirror'. Like I said 'what can I say' twice, and the first time i got the gray glow and the second time it spat out the list of commands. Then about a minute later all I had to do was say 'go home' twice a minute later and it went back to home screen. 

I'm guessing theres something wrong with my sensitivity and my config.js file. Any ideas?

**Comment by petran1420** [comment] 2016-11-11 04:27
Ok, I just tried adjusting to `speech : {continuous : true}` in config.js, and now it isn't detecting anything...

**Comment by hyp3rx** [comment] 2016-11-11 07:16
I have exactly the same issue. 
After some time (5 or 10 minutes) the grey glow turns on even if i don´t say anything... after a while (glows for more then 2-3 minutes) it doesn´t glow anymore...

**Comment by justbill2020** [comment] 2016-11-11 19:19
hey guys... did you follow all the configuration steps in https://docs.smart-mirror.io?

continuous:true is really not a great thing to have done it will burn through your API calls when its working... i would set that back to false...

have you followed the steps for configuring the pi? https://docs.smart-mirror.io/docs/configure_the_pi.html

there might be something with the screensaver impacting this issue...

**Comment by petran1420** [comment] 2016-11-11 23:42
I believe I did everything correctly with installation and configuring the pi, but i'll recheck, maybe reinstall the screen saver program...would the app still be working if the non-screen saver install wasn't done correctly? Here's my speech input for the config file:

` // Keyword Spotting (Hotword Detection)
    speech : {
        projectId: 'mirror-146901',
        keyFilename: '/home/pi/smart-mirror/Mirror-a62eb0ca6ccb.json',
        keyword : "Smart Mirror",
        model : "smart_mirror_em.pmdl", // The name of your model
        sensitivity : 0.5, // Keyword getting too many false positives or not d$
        continuous: false // After a keyword is detected keep listening until s$
    },`

I had the app running all day for the first time, when I went to work. I came back, the screen and everything seems to be working fine but now its not recognizing hotwords at all...

**Comment by petran1420** [comment] 2016-11-12 02:04
Just checked the screen saver under `/home/pi/.config/lxsession/LXDE-pi/autostart` and everything appears to be in order. 

Left again, came back a few hrs later, and the same problem. At start up the app is recognizing almost any word as the hotword, usually won't stop listening, and then stops listening altogether after an extended period of time.

**Comment by hyp3rx** [comment] 2016-11-14 13:16
yep... i agree with @petran1420 ... i have the same issue, and have fallowed every step ! After Start, the app recognized everything, then it stops listining (white bar)

**Comment by evancohen** [comment] 2016-11-14 23:48
Thanks for the super detailed issue, I wish they were all like this!
I'm pretty sure this is a duplicate of #420 so I'm going to close this out so we can consolidate the conversation.

**Closed by evancohen** 2016-11-14 23:48 UTC
