### ISSUE TITLE
not working after sleep mode 

### ISSUE THREAD

**Issue by nevido** [evancohen/smart-mirror#611] opened 2017-03-19 12:01 UTC
good working befor sleep mode

but doesn't voice  work after sleep mode

hotword ok(wake up)  and then not working any voice command 

pls help me

**Comment by justbill2020** [comment] 2017-03-19 15:46
Closing issue. This is a duplicate of #592 please search issues before opening new issues.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Closed by justbill2020** 2017-03-19 15:46 UTC
Labels: resolution: duplicate
