### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by lorama** [evancohen/smart-mirror#438] opened 2016-11-19 07:30 UTC
I'm not sure if it's just my mirror but when I add or request to be shown the reminders, nothing happens. 
Thank you (:
Also, the command for showing reminders is "show me reminders" while the command for videos is "show me____"

**Comment by evancohen** [comment] 2016-11-19 13:47
Interesting... @justbill2020 have you seen this? I'm not sure this was ever even fully implemented...
Could be a regression too. I'm on vacation for Thanksgiving this week but I'm trying to carve out some time to work on the smart mirror - hopefully I'll have time to take a look :)

**Comment by justbill2020** [comment] 2016-11-19 18:22
Lol "carve out" I see what you did there... I don't use reminders but I'll test on pi and my ubuntu dev vm. @lorama what platform are you running the smart-mirror on?

**Comment by lorama** [comment] 2016-11-19 19:53
I'm running it through the raspberry pi :) @justbill2020

**Comment by justbill2020** [comment] 2016-11-19 23:38
@evancohen ok I just tested it in ubuntu... it is very haphazard... sometimes when running it in dev mode it loads the "remind me to _______" command other times it doesn't

often when speaking "remind me to watch tv" google only translates "remind me"

when speaking "show reminders" I don't get a display of what google speech heard and i get this youtube video... https://www.youtube.com/watch?v=d8kCTPPwfpM

12 minutes or so later after watching the video like 4 times... I looked through and the code looks right. I'm unable to step through to test it though also and I can't get `annyang.simulate("COMMAND HERE");` to work...

**Comment by evancohen** [comment] 2016-11-20 02:51
LOL. I love Ellen... 
Since we updated annyang it's now `annyang.trigger("COMMAND HERE")`
I'm guessing the order or command registration got mixed up so it's "falling back" to YouTube before considering reminders.

**Comment by justbill2020** [comment] 2016-11-20 03:05
Ok that's cool docs need to be updated to show trigger not simulate.

**Comment by jcbriones** [comment] 2016-11-20 20:59
Having the same issue.

**Comment by evancohen** [comment] 2016-11-26 08:06
Fixed in dev :)

**Closed by evancohen** 2016-11-26 08:06 UTC
Labels: bug
