### ISSUE TITLE
annyang.simulate syntax error in console

### ISSUE THREAD

**Issue by geman220** [evancohen/smart-mirror#303] opened 2016-06-23 23:00 UTC
When issuing a command like:

```annyang.simulate("show me a map of Seattle Washington");``` in the dev console I get the following error:

```Uncaught Syntax error: Invalid or unexpected token```

**Comment by evancohen** [comment] 2016-06-24 00:44
On the latest master with the default config I am unable to reproduce this.

![image](https://cloud.githubusercontent.com/assets/1198365/16324511/f5805c2a-3969-11e6-9b92-db56ae2bcb84.png)

Have you made any changes to the codebase that may cause this issue?

**Comment by geman220** [comment] 2016-06-24 01:09
No I haven't in fact I just did the following to be sure
```
git clean -xdf -e config.js
npm install
```

**Comment by evancohen** [comment] 2016-06-24 01:14
This puzzles me... @kurtdb are you able to get this to work?

**Comment by evancohen** [comment] 2016-06-24 01:24
Nevermind! Got this sorted out in chat. Turns out the encoding of the closing quotation mark was weird: http://i.imgur.com/8VpszUf.png

**Closed by evancohen** 2016-06-24 01:24 UTC
