### ISSUE TITLE
0.19 GeolocationService injection passed in null

### ISSUE THREAD

**Issue by sdetweil** [evancohen/smart-mirror#764] opened 2019-01-12 15:37 UTC
the map and traffic plugins are failing with Geolocation.getLocation() unable to read property 'getLocation' of null

### Steps to Reproduce (for bugs)

1. start SM in dev mode, 
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

0.19, ubuntu, ODROID hardware. 
uname -a
Linux odroid 4.14.87-153 #1 SMP PREEMPT Tue Dec 11 11:33:18 -02 2018 armv7l armv7l armv7l GNU/Linux

prior version works fine

**Comment by evancohen** [comment] 2019-01-13 03:49
@sdetweil dupe of #748?

**Comment by sdetweil** [comment] 2019-01-13 04:04
No. Not dup. Different problem.   There if Geo no specified, tries to get it. But that call is rejected now... But service has to work for that....

**Comment by evancohen** [comment] 2019-01-13 04:08
Broken. So broken 😭

**Comment by sdetweil** [comment] 2019-03-02 04:00
actually the https://maps.googleapis.com/maps/api/browserlocation/json?browser=chromium

api no longer works. 

https://developers.google.com/maps/documentation/javascript/examples/map-geolocation

**Comment by sdetweil** [comment] 2019-03-02 04:43
the new api, which also requires an api_key and api enablement is  a POST to 

https://www.googleapis.com/geolocation/v1/geolocate?key="+keyFile.api_key)

with a json body of some form..  minimum = {}

there aren't any posts in the code so far, and I don't understand what $http is  is it an xmlRequest or?

**Comment by sdetweil** [comment] 2019-03-06 12:10
the root cause of this problem was a name collision with our Map controller.js class..  some library is using a Map() object and our Controller class got used.. but not as expected, it then called GeoLocation.. but didn't pass the parms as expected...  fix was to change name of the Map controller class to MapController from Map

**Closed** 2019-03-08 20:12 UTC
Labels: Type: bug
