### ISSUE TITLE
npm start is not working

### ISSUE THREAD

**Issue by zol60fire** [evancohen/smart-mirror#47] opened 2016-01-26 14:41 UTC
"npm start" is not working. 
![12476105_981276245265253_1284190905_n](https://cloud.githubusercontent.com/assets/15710483/12583440/ca844f06-c47d-11e5-9b6c-388729cb9e7c.jpg)

**Comment by evancohen** [comment] 2016-01-26 19:59
It looks like the `npm install` process did not properly complete. Are you using the Pi 2?

**Comment by goprojojo** [comment] 2016-02-03 20:19
Hi, I also have problem running npm start. I tried running npm install electron-prebuilt but still no avail. Latest version of node.js and npm are installed. 
<img width="477" alt="smart-mirror" src="https://cloud.githubusercontent.com/assets/14301878/12795747/bf469808-cabb-11e5-836c-eada973f6c89.png">

**Comment by evancohen** [comment] 2016-02-04 02:01
@goprojojo This might sound silly, but are you running in GUI mode? You can't start the mirror from ssh and you must be running the GUI. This can be started with `startx`.

**Comment by evancohen** [comment] 2016-02-07 00:23
Closing this issue as I can only guess these issues have been resolved.

**Closed by evancohen** 2016-02-07 00:23 UTC

**Comment by seihser** [comment] 2016-09-13 20:23
Greetings everyone!

Sorry but i have th same probeme, I'm not running the smart mirror on a raspberry but on an old MSI wind U 100 with ubuntu on it.

I started using your files 6 months ago and it worked well (got the geoposition problem only), but i saw that you implemented new functions recently so I created an other folder in order to copy the new files (following the doc).

So i got those errors when i try to run the smart-mirror:

laurent@LaurentMirror:~/smart-v2/smart-mirror$ npm start

> smart-mirror@0.0.3 start /home/laurent/smart-v2/smart-mirror
> electron main.js 

sh: 1: electron: not found

npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! smart-mirror@0.0.3 start: `electron main.js `
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.3 start script 'electron main.js '.
npm ERR! This is most likely a problem with the smart-mirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-mirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls smart-mirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/laurent/smart-v2/smart-mirror/npm-debug.log


Here is the log file:

**Comment by seihser** [comment] 2016-09-13 20:29
If you want me to give you the old confif.js file which work well (except the weather) and the new one that crash at "npm start" let me know.

thanks for all the support evan on this awesome project!

**Comment by evancohen** [comment] 2016-09-13 21:00
Try reinstalling your dependencies:
```
git clean -xdf -e config.js
npm install
```

The package that we use is still `electron-prebuilt` even though they have moved to `electron` for prebuilt binaries, and I think it's still supported but that could also be the cause of this issue.
