### ISSUE TITLE
Mirror not importing all calendar events

### ISSUE THREAD

**Issue by bmccuskey** [evancohen/smart-mirror#172] opened 2016-03-20 18:36 UTC
After updating  smart-mirror a couple days ago, most of my calendar events are missing. The mirror is pulling from the icals I add to the list, but it doesn't show all the events. For example, it shows only one event for tomorrow, then another event a couple weeks from now but it misses all the events in between.

I went through and completely removed the smart-mirror directory and uninstalled everything associated with the smart-mirror and went back through installing everything again. Then I manually updated the config file based off the template, but still no luck.

**Comment by evancohen** [comment] 2016-03-21 03:00
What was the version that you were using before (ie, the commit ID)? There have been some recent fixes for Exchange and iCloud that may have caused a regression here.

It would be helpful if you could PM me your iCAL URL in gitter and tell me which events aren't showing up so I can test this.

@yaydogan @kurtdb who might be able to help.

**Comment by kurtdb** [comment] 2016-03-21 10:23
That's a new one to me. I know there is still an issue between fetching from multiple calendars and the events showing up twice through time.

Would it be possible to share a minimum viable testset so we can verify and fix the issue?

**Comment by bmccuskey** [comment] 2016-03-21 12:57
I'm trying to backtrack when I updated. (I hadn't really kept track of the commit IDs when I updated.) I do know that I updated my pi2 on the 9th or 10th which is when I first ran into the time issue, then I transitioned to a raspberry pi3. The calendar was still working then. I updated and then downgraded moment on the 17th and I believe that was when the calendar stopped working.

I have been adding three calendars to pull from, and previously didn't notice any issues. Maybe I could cut it down to just one ical and see if it works.

**Comment by yaydogan** [comment] 2016-03-22 01:32
On a business trip this week but I will take a look at it when I get a chance. Don't have access to my setup now but I also saw some events missing from my exchange calendar. Seemed to be the ones where organizer is in a different timezone. It could be a coincidence too, not sure yet. @bmccuskey if you observe the same, that may give us a hint to debug further.

**Comment by bmccuskey** [comment] 2016-03-22 01:52
I think the issue might lie with events that repeat. Though, it isn't consistent.

**Comment by evancohen** [comment] 2016-03-22 01:56
That's likeley the issue. Today I don't think there is any code specific to parsing time zone offsets for the calendar. It works when things are specified in UTC or within your own time zone, which is pretty standard - but there's a specific format that uses text to specify the time zone which we ignore right now.

**Comment by bmccuskey** [comment] 2016-03-22 02:02
Hmm. Was that a recent change or what might have caused it to work before? One of the calendars that I pull from the mirror only shows non-repeating events, on one of my other calendars it actually shows one of the repeating events, but not others.

**Comment by evancohen** [comment] 2016-03-22 22:23
Well, there's #155 and #131 which don't really mess with it, and #89 which fixed recurring events. None of these really touch this issue. I'm guessing that it never actually worked to begin with...

**Comment by yaydogan** [comment] 2016-04-01 12:41
Few examples of timezone string I captured from my calendar events:

DTSTART;TZID="(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna":20160314T140000
DTSTART;TZID=Eastern Standard Time:20160318T090000

We need to process the TZID parameter to address this issue. In MS EXchange, the timezone is set to the meeting organizer's timezone.

**Comment by pearno** [comment] 2016-04-29 12:52
Hi folks,

I'm a brand new smart-mirror user/builder, and I can confirm that I have the same problem, specifically with recurring events.  The source is a shared iCloud calendar.  I temporarily added my work Exchange  calendar and saw a similar pattern - recurring events not showing up, but ad-hoc events just fine.

To confirm the problem, I created a new calendar, published it, then created three ad-hoc and three recurring events.  On my mirror I see six events (out of the expected nine) - the three ad-hoc, and the first instance of each recurring event.

Since this is a test calendar, I'm happy to share the link:

https://p02-calendars.icloud.com/published/2/6rIM6xgO2MKv6z_ZOKvCLjeMyZGH60R0V57oG8tVurmTK62Vag5eun90E4sKNdPSgyS18TiRIEGBn7RQZNzbTfgXc5u9AEuUNIdDQvZtaio

Not really sure what I should be looking for though... Happy to test any suggestions people might have!

**Comment by bmccuskey** [comment] 2016-04-29 13:09
I've become increasingly aware of how many recurring events I have programed in my calendars. I have noticed that sometimes, some repeating events show up, but not always.

**Comment by evancohen** [comment] 2016-04-29 23:16
Thanks for sharing that @pearno, it'll be super helpful for debugging this issue. @kurtdb is on vacation so maybe @yaydogan can take a look. If not I'll add it to my todo list :)

**Comment by yaydogan** [comment] 2016-04-30 02:28
Hi all,
I have been away from the forum for a while due to busy schedule. I know the timezone issue for sure but don't have a fix for it yet. I can take a look at the test calendar @pearno  provided next week. Will keep you all posted.

**Comment by smalik03** [comment] 2016-05-21 02:28
Hey guys, I am having the same issue with my calendar as well. For me, the problem is with recurring events, they do not show up. I debugged the Calendar service and noticed the condition for 'RRULE'  on line number 107

`if (cur_event['SUMMARY'] !== undefined && cur_event['RRULE'] !== undefined &&
              cur_event['DTSTART] !== undefined && cur_event['DTEND'] !== undefined)`

The issue from my debugging seems to be, 'DTSTART' and 'DTEND' are not always the property names used to identify date start and end. In my case, they were 'DTSTART; VALUE' and 'DTEND; VALUE'. Its the same with the .ics from @pearno (line# 326). 

I think saving the property names for these and then using them in the condition would work. Not sure though if it affects anything else. I am fairly new to smart-mirror and haven't looked around the code a  lot. Thought would share my findings, might help to resolve the issue faster.

**Comment by kurtdb** [comment] 2016-05-26 18:20
This should be fixed in my dev-branch (https://github.com/kurtdb/smart-mirror/tree/dev)

If anyone who has the problem can verify it works for them, that would be awesome.

The example ical that was shared in the bug report now works for me. (shows recurring events for event 1 and 3)

<img width="1440" src="https://cloud.githubusercontent.com/assets/5654891/15585364/2f06e3fc-237f-11e6-9139-d9e71a2a2a21.png">

**Comment by pearno** [comment] 2016-05-27 13:54
I've just tested this and it works a treat, both on my test calendar and my original calendar that I was having issues with.  Great stuff!

**Comment by kurtdb** [comment] 2016-05-27 14:45
Okay, I will merge it into Evan's dev branch later today.

**Comment by kurtdb** [comment] 2016-05-31 10:31
Closed due to the fact that this is now integrated in the dev-branch.

**Closed by kurtdb** 2016-05-31 10:31 UTC
Labels: bug, next
