### ISSUE TITLE
Speech recognition stop working after a while

### ISSUE THREAD

**Issue by overflOw11** [evancohen/smart-mirror#670] opened 2017-08-03 11:29 UTC
My speech recognition works perfectly except after a while (a day approximately). Sonus and google speech api are configured and works very well but a after few hours, the hotword isn't be recognized anymore.

I suspect the autoTimer module to don't wake up the mirror but when i desactivate it, speech recognition still stop working after a few hours.

I'am on the dev branch with the star service that I develop enable but there is no more modification on the code.
It's running on a raspberry pi 3 with node 8.2.1 (recently updated from node 6).

**Comment by evancohen** [comment] 2017-08-05 02:30
I've seen this happen intermittently and I believe it's an issue with Google Cloud Speech/gRPC but have had an exceptionally difficult time reproducing it (because it takes so long).

Going to have another look at it this weekend to see if I can figure out what is going on.

**Comment by overflOw11** [comment] 2017-08-06 16:05
I've made some tests and I don't think it's a Googlge Cloud speech bug because when the mirror stop listening to me, I can send a vocal command from the remote website (<IP_mirror>:9999) in the "Type command" input with the microphone icon. 
I took a look in the remote website code, and I see that this microphone icon just bypass the detection of the keyword spotter by Sonus, so I think it's a Sonus bug for me.

Let me know if you find something, I have to restart my mirror every day to make sure it works.

**Comment by justbill2020** [comment] 2017-08-07 00:45
The remote uses annyang and WebKit for voice not google speech API...

**Comment by overflOw11** [comment] 2017-08-07 07:12
Ok, my mistake.
I keep digging in the code and in Google Cloud speech service.

Thx

**Comment by evancohen** [comment] 2017-08-07 20:18
Yeah, the remote uses a different code path for command input. It's definitely a Sonus related issue, but what I'm having trouble figuring out is what *part* of sonus is the issue (weather it's a dependency or something wrong with the library itself).

**Comment by sdetweil** [comment] 2017-11-18 12:23
the code issue is here in the sonus library 

CloudSpeechRecognizer.startStreaming = (options, audioStream, cloudSpeechRecognizer) => {
  if (cloudSpeechRecognizer.listening) {
    return
  }

for some  active listening remains on,  if u comment this out, then it will recover..  

I think its because the end_of_utterance doesn't occur..  noise maybe?

      if (data.endpointerType === 'END_OF_UTTERANCE') {
        cloudSpeechRecognizer.listening = false

**Comment by evancohen** [comment] 2017-11-20 08:18
I've fixed this issue in evancohen/sonus#67 and have published a new version of the npm package. From the smart mirror folder if you run the following, your issue should be fixed:
```
npm install sonus@0.1.9
```
I'll bump the version for the smart mirror and push the fix this week.

**Comment by sdetweil** [comment] 2017-12-18 13:08
posted pull request which fixes this problem, requires change to the sonus module.

**Comment by sdetweil** [comment] 2017-12-27 13:44
also noticing that arecord just terminates without notice..  debugging.

**Comment by sdetweil** [comment] 2018-01-18 13:04
added solution to pull request.   also the sonus background task was ending without notice.. added handlers to main.js to detect and restart

**Comment by evancohen** [comment] 2019-03-06 02:16
So it turns out that I didn't fix this properly last time... Turns out the issue was a bit more complicated than I had originally thought. You can test this fix with
```
npm install sonus@1.0.1-beta.1
```

Once it gets a bit of testing I'll publish the next release and it'll be integrated into the smart mirror 🍾

**Closed** 2019-03-08 20:13 UTC
